apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accounts-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "accounts-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "accounts-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: {{ .Values.service.port | quote }}
      labels:
        app.kubernetes.io/name: {{ include "accounts-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "accounts-service.name" . }}
          image: "{{ printf "%s/%s" .Values.global.imageRegistry "accounts-service" }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "accounts-service.fullname" . }}
          env:
            - name: APP_ENV
              value: {{ .Values.global.envName | default "unknown" | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ printf "jdbc:postgresql://%s:%d/%s" .Values.db.host .Values.db.port .Values.db.database | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.passwordSecretName }}
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.passwordSecretName }}
                  key: {{ .Values.db.passwordSecretKey }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else if .Values.global.resources }}
            {{- toYaml .Values.global.resources | nindent 12 }}
            {{- end }}
