apiVersion: v2
name: grafana
description: Grafana visualization tool
type: application
version: 0.1.0

dependencies:
  - name: grafana
    version: 8.5.1
    repository: https://grafana.github.io/helm-charts
