spring:
  application:
    name: transfer-service
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/