spring:
  application:
    name: notifications-service
  kafka:
    listener:
      observation-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      env: ${APP_ENV:unknown}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://bank-zipkin.zipkin.svc.cluster.local:9411/api/v2/spans}
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:bank-kafka.kafka.svc.cluster.local:9092}
    notifications-topic: ${KAFKA_NOTIFICATIONS_TOPIC:bank.notifications}
    group-id: ${KAFKA_NOTIFICATIONS_GROUP_ID:notifications-service}