apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-service.fullname" . }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.springProfile | quote }}
  KAFKA_BOOTSTRAP_SERVERS: "bank-kafka.kafka.svc.cluster.local:9092"
  KAFKA_NOTIFICATIONS_TOPIC: "bank.notifications"
