apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cash-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cash-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cash-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "cash-service.name" . }}
          image: "{{ printf "%s/%s" .Values.global.imageRegistry "cash-service" }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfile | quote }}
          resources:
            {{- if .Values.resources }}
              {{- toYaml .Values.resources | nindent 12 }}
              {{- else if .Values.global.resources }}
              {{- toYaml .Values.global.resources | nindent 12 }}
              {{- end }}
