apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "auth-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "auth-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: {{ .Values.service.port | quote }}
      labels:
        app.kubernetes.io/name: {{ include "auth-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "auth-server.name" . }}
          image: "{{ printf "%s/%s" .Values.global.imageRegistry "auth-server" }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "auth-server.fullname" . }}
          env:
            - name: APP_ENV
              value: {{ .Values.global.envName | default "unknown" | quote }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- else if .Values.global.resources }}
            {{- toYaml .Values.global.resources | nindent 12 }}
            {{- end }}
