apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "auth-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "auth-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
